## This is a supervised learning model to predict the values of house prices based on a bunch of parameters that we give

> We find the square of difference between actual and predicted values, these values are added and then averaged, this is the cost function. Objective is cost = 0. <br>

> We will be using **Gradient Descent** to optimize the cost function ie. reduce the cost so that it tends to 0.<br>

> **Gradient Descent** is an ensemble of decision trees!!! (a bunch of ML algos which are used together to get better results)

> **Strategy**: We randomly give weights, gradient descent iteratively tweaks the weights in an attempt to get the cost function to equal zero. <br>

> After optmizing the cost to near zero, it will throw back the weights and these weights are what will be used in the model

> **Cost Function**: An equation that tells you how wrong an estimator function is with the current weights <br>

> Hyper parameters: define how fast the model is to learn, and how much of a complicated model do you want to build

> Decision trees are implemented as 1 complex tree which defines complicated relationships, or we can have an ensemble of trees askin to asking your friends for an opinion on the same question. Gradient boosting is similar to this ensemble approach, difference being that you actually use the output of one tree as an input to the next tree <Br>

> Learn about complex trees, ensemble trees, Gradient Boosting(ensemble with sequential output used as input to next tree) Check the video in 2nd part, about Gradient Boosting

In [126]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn import ensemble
from sklearn.metrics import mean_absolute_error

In [127]:
house_df = pd.read_csv('C:/Users/user/Desktop/ml_house_data_set.csv')

In [128]:
house_df

,year_built,stories,num_bedrooms,full_bathrooms,half_bathrooms,livable_sqft,total_sqft,garage_type,garage_sqft,carport_sqft,has_fireplace,has_pool,has_central_heating,has_central_cooling,house_number,street_name,unit_number,city,zip_code,sale_price
0,1978,1,4,1,1,1689,1859,attached,508,0,True,False,True,True,42670,Lopez Crossing,NaN,Hallfort,10907,270897.0
1,1958,1,3,1,1,1984,2002,attached,462,0,True,False,True,True,5194,Gardner Park,NaN,Hallfort,10907,302404.0
2,2002,1,3,2,0,1581,1578,none,0,625,False,False,True,True,4366,Harding Islands,NaN,Lake Christinaport,11203,2519996.0
3,2004,1,4,2,0,1829,2277,attached,479,0,True,False,True,True,3302,Michelle Highway,NaN,Lake Christinaport,11203,197193.0
4,2006,1,4,2,0,1580,1749,attached,430,0,True,False,True,True,582,Jacob Cape,NaN,Lake Christinaport,11203,207897.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
42698,1982,1,1,1,0,591,627,none,0,200,False,False,True,True,562,Gregory Ford,253.0,Lake Jack,10825,88197.0
42699,1983,1,1,1,0,592,624,none,0,204,False,False,True,True,62028,Gregory Ford,3560.0,Lake Jack,10825,102690.0
42700,1983,1,1,1,0,594,618,none,0,197,False,False,True,True,62028,Gregory Ford,3931.0,Lake Jack,10825,98280.0
42701,1981,1,3,2,0,1398,1401,attached,401,0,False,False,True,True,7456,Garcia View,NaN,Lake Jack,10825,98278.0
42702,1980,1,3,2,0,1401,1406,attached,396,0,False,False,True,True,7456,Garcia View,NaN,Lake Jack,10825,186480.0

In [129]:
house_df.columns.size

20

# Create a webpage view of data for easy viewing:

In [130]:
import os
import webbrowser
html = house_df[0:100].to_html()

with open('house_df.html','w') as f:
    f.write(html)
full_filename = os.path.abspath('house_df.html')
webbrowser.open('file://{}'.format(full_filename))

True

# Learnings for Feature Engineering:
Data should be 10x the number of all features.

In [131]:
house_df.drop(['street_name','unit_number','zip_code','house_number'], axis =1, inplace = True)

In [132]:
house_df

,year_built,stories,num_bedrooms,full_bathrooms,half_bathrooms,livable_sqft,total_sqft,garage_type,garage_sqft,carport_sqft,has_fireplace,has_pool,has_central_heating,has_central_cooling,city,sale_price
0,1978,1,4,1,1,1689,1859,attached,508,0,True,False,True,True,Hallfort,270897.0
1,1958,1,3,1,1,1984,2002,attached,462,0,True,False,True,True,Hallfort,302404.0
2,2002,1,3,2,0,1581,1578,none,0,625,False,False,True,True,Lake Christinaport,2519996.0
3,2004,1,4,2,0,1829,2277,attached,479,0,True,False,True,True,Lake Christinaport,197193.0
4,2006,1,4,2,0,1580,1749,attached,430,0,True,False,True,True,Lake Christinaport,207897.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
42698,1982,1,1,1,0,591,627,none,0,200,False,False,True,True,Lake Jack,88197.0
42699,1983,1,1,1,0,592,624,none,0,204,False,False,True,True,Lake Jack,102690.0
42700,1983,1,1,1,0,594,618,none,0,197,False,False,True,True,Lake Jack,98280.0
42701,1981,1,3,2,0,1398,1401,attached,401,0,False,False,True,True,Lake Jack,98278.0
42702,1980,1,3,2,0,1401,1406,attached,396,0,False,False,True,True,Lake Jack,186480.0

In [133]:
features_df = pd.get_dummies(house_df,'garage_type','city')

In [134]:
features_df.drop(['sale_price'], axis =1, inplace=True)

In [135]:
X = np.array(features_df)

In [136]:
y = np.array(house_df['sale_price'])

In [137]:
y

array([ 270897.,  302404., 2519996., ...,   98280.,   98278.,  186480.])

In [138]:
X_train, X_test, y_train, y_test =  train_test_split(X, y, test_size = 0.3)

In [139]:
model = ensemble.GradientBoostingRegressor(
    n_estimators = 1000,
    learning_rate = 0.1,
    max_depth = 6,
    min_samples_leaf = 9,
    max_features = 0.1,
    loss = 'huber'
)

In [140]:
model.fit(X_train,y_train)

GradientBoostingRegressor(loss='huber', max_depth=6, max_features=0.1,
                          min_samples_leaf=9, n_estimators=1000)

In [141]:
# Find the error rate on the training set
mse = mean_absolute_error(y_train, model.predict(X_train))
print("Training Set Mean Absolute Error: %.4f" % mse)

# Find the error rate on the test set
mse = mean_absolute_error(y_test, model.predict(X_test))
print("Test Set Mean Absolute Error: %.4f" % mse)

Training Set Mean Absolute Error: 48649.6348
Test Set Mean Absolute Error: 57236.5963

> The model was able to predict the train data with higher accuracy as compared to the test data, which is expected

# Learning for Accuracy

> Overfitting: if the training error is very low while the test error is very high <br>

> Underfitting: if the training error and test error both as high, then it is underfitted model


# Intuition:
If the model seems to overfit, then you might want to 
1. reduce the number of decision trees, n_estimators to make it generalize better or  <br>
2. make the trees less complicated

> Good fit: If the train and test error, both are low, then we have a good fit model.

n_estimators: total trees
max_depth = max decision nodes
min_samples_leaf = minimum instances to learn a decision, to avoid outliers having an impact

model = ensemble.GradientBoostingRegressor()

# Parameters we want to try
param_grid = {
    'n_estimators': [500, 1000, 3000],
    'max_depth': [4, 6],
    'min_samples_leaf': [3, 5, 9, 17],
    'learning_rate': [0.1, 0.05, 0.02, 0.01],
    'max_features': [1.0, 0.3, 0.1],
    'loss': ['ls', 'lad', 'huber']
}

from sklearn.model_selection import GridSearchCV
gs_cv = GridSearchCV(model, param_grid, n_jobs=4)

gs_cv.fit(X_train, y_train)

In [ ]:
print(gs_cv.best_params_)

# Practical implications of using the model:
you should test the accuracy of new models before replacing an existing model <br>
you should consider retraining the model regularly as data changes <br>
you need to provide the input features in exactly the same format they were provided in during training